name: Docker FullStack App Test
on: [push]
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: actions/checkout@v2

      - name: Build docker test image
        run: docker build -t appchemist/react-test-app -f ./frontend/Dockerfile.dev ./frontend

      - name: Run test
        run: docker run -e CI=true appchemist/react-test-app npm test

      - name: Build docker image
        run: |
          docker build -t appchemist/docker-frontend ./frontend
          docker build -t appchemist/docker-backend ./backend
          docker build -t appchemist/docker-nginx ./nginx

      - name: Push docker image
        run: |
          docker push appchemist/docker-frontend
          docker push appchemist/docker-backend
          docker push appchemist/docker-nginx

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate deployment package
        run: zip -r deploy.zip .

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: Deploy to ES BeanStalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DockerFullStack
          environment_name: Dockerfullstack-env
          region: ap-northeast-1
          version_label: docker-app-${{steps.current-time.outputs.formattedTime}}
          deployment_package: deploy.zip