name: Docker FullStack App Test
on: [push]
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: actions/checkout@v2

      - name: Build docker test image
        run: docker build -t appchemist/react-test-app -f ./frontend/Dockerfile.dev ./frontend

      - name: Run test
        run: docker run -e CI=true appchemist/react-test-app npm test

      - name: Build docker image
        run: |
          docker build -t appchemist/docker-frontend ./frontend
          docker build -t appchemist/docker-backend ./backend
          docker build - tappchemist/docker-nginx ./nginx

      - name: Push docker image
        run: |
          docker push appchemist/docker-frontend
          docker push appchemist/docker-backend
          docker push appchemist/docker-nginx